<?php


include('login.php');


include('css.php');



    

?>
<!DOCTYPE html> 
<html>
<title>SnitchHunt</title>
<meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width = device-width;"> 
<head>





</head>

<body> 

<h2 class='top_title'>Government</h2>
  <?php
include('footer.php');

?>

<div id='nav'>
 

<?php

include'framework.php';
?>

</div>
<table border='0px' class='top-nav'><tr><td>

   <?php
    echo" 
<form action='index.php' method='POST'>
   <input type='hidden' name='team_name' value='".$_POST['team_name']."'> 
   <input type='hidden' name='password' value='".$_POST['password']."'> 
<input class='nav_button_left'   type='submit'  name='submit' value='' id='submit' />

  

</form> ";
?>
 <!-- <a href='https://whistleblower.network/snitch/eight.php'><img style='margin-top:-30px;' src='https://whistleblower.network/snitch/images/next-blue-light-left.png'></img></a>
-->
 </td>
  <td>

    <!--<a href='https://whistleblower.network/snitch/hard_quiz.php'><img src='https://whistleblower.network/snitch/images/next-blue-light.png'></img></a>-->
   <?php
    echo" 
<form action='three.php' method='POST'>
   <input type='hidden' name='team_name' value='".$_POST['team_name']."'> 
   <input type='hidden' name='password' value='".$_POST['password']."'> 
<input class='nav_button_right'   type='submit'  name='submit' value='' id='submit' />

  

</form> ";
?>
  </td></tr></table>
<div class='page'>
<div class='left'>
  <div class='video_small'>
  <iframe 
  src="https://embed.theguardian.com/embed/video/world/video/2017/apr/04/wiretaps-data-dumps-and-zero-days-is-digital-privacy-no-longer-possible-video" 
   max-width="400" height="300" frameborder="0" allowfullscreen></iframe>
 </div>
 <div class='video_large'>
  <iframe  
  src="https://embed.theguardian.com/embed/video/world/video/2017/apr/04/wiretaps-data-dumps-and-zero-days-is-digital-privacy-no-longer-possible-video" 
 width="500" height="315" frameborder="0" allowfullscreen></iframe>
 </div>

<p class='small'><i>"Terrorism is tipping the balance from privacy and toward ongoing mass surveillance."</i></p>
<h5>What is metadata?</h5>
<p>Telecommunications metadata is generated by our devices when we send emails, make calls or simply take our phone 
with us (as it pings the nearby cell towers). 
The data collected is described by the Attorney-General in this <a href='https://www.ag.gov.au/NationalSecurity/DataRetention/Documents/Dataset.pdf' target='_blank'>pdf</a>. </p>

</div>
<div class='right'>
 

  <p>There are different levels of access government agencies can have of the information generated whenever we contact someone with an electronic device:</p>
<button class="accordion">1. 'warrantless metadata'</button>
<div class="panel">
    <p>So called 'metadata' that has been generated within the last two years is available to law enforcement agencies without a warrant. </p>
    <p>Government agencies are only required to obtain a warrant when they wish to access metadata of professional journalists. Despite this, in the first
      weeks after the Metadata Retention Scheme came into effect in early 2017, the AFP was found to have <a href='http://www.zdnet.com/article/afp-mistakenly-accessed-journalist-call-records-breaching-metadata-laws/' target='_blank'>accessed the metadata belonging to a journalist without a warrent</a>.</p>
</div>

<button class="accordion">2. data made available once a warrant is granted</button>
<div class="panel">
      <p>All of the 'metadata' created and stored for the past two years on any device with Australian ISP, email or phone accounts as well as 
      	the 'content' &amp; subject line of emails, 
        voice-mail and your web browsing history can be accessed by law enforcement agencies with a warrant.</p>




  <p>It should be noted that the definition between the above categories is not set in stone. What is considered content today can be moved into the category for warrantless access as the definition of
    what is or is not metadata is not made clear in the legislation and can be changed without the need to change the underlying Act.</p>
 </div>
<button class="accordion">3. data collected &amp; stored internationally</button>
<div class="panel">
<p>The <a href='https://en.wikipedia.org/wiki/Five_Eyes'>Five Eyes</a> intelligence alliance comprising Australia, Canada, New Zealand, the United Kingdom and the United States has great
	powers to access our data. According to Wikipedia:</p>
	<p><i>
	"The Five Eyes has two types of information collection methods. The first is the PRISM program and the second is the Upstream system. The PRISM program gathers user information from technology firms such as Google, Apple and Microsoft, while the Upstream system gathers 
	information directly from the communications of civilians via fiber cables and infrastructure as data flows past."</i></p></details>
</div>


</div>
<table border='0px' class='bottom-nav'><tr><td>

   <?php
    echo" 
<form action='index.php' method='POST'>
   <input type='hidden' name='team_name' value='".$_POST['team_name']."'> 
   <input type='hidden' name='password' value='".$_POST['password']."'> 
<input class='nav_button_left'   type='submit'  name='submit' value='' id='submit' />

  

</form> ";
?>
 <!-- <a href='https://whistleblower.network/snitch/eight.php'><img style='margin-top:-30px;' src='https://whistleblower.network/snitch/images/next-blue-light-left.png'></img></a>
-->
 </td>
  <td>

    <!--<a href='https://whistleblower.network/snitch/hard_quiz.php'><img src='https://whistleblower.network/snitch/images/next-blue-light.png'></img></a>-->
   <?php
    echo" 
<form action='three.php' method='POST'>
   <input type='hidden' name='team_name' value='".$_POST['team_name']."'> 
   <input type='hidden' name='password' value='".$_POST['password']."'> 
<input class='nav_button_right'   type='submit'  name='submit' value='' id='submit' />

  

</form> ";
?>
  </td></tr></table>
</div>

</div>
</div>


</div>
  <script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
    acc[i].onclick = function(){
        this.classList.toggle("active");
        var panel = this.nextElementSibling;
        if (panel.style.display === "block") {
            panel.style.display = "none";
        } else {
            panel.style.display = "block";
        }
    }
}
</script>
</body>
</html>
